require("plyr")
require("data.table")
f <- fread("household_power_consumption.txt" , sep=";", na.strings="?", header=TRUE)
DT <- f[as.Date(Date,"%d/%m/%Y") >= "2007-02-01" & as.Date(Date,"%d/%m/%Y") <= "2007-02-02"]
DT$datetime <- as.POSIXct(paste(as.Date(DT$Date,"%d/%m/%Y"),DT$Time))
png("plot3.png" , width=480 , height = 480)
plot(DT$datetime,DT$Sub_metering_1,type="l", ylab = "Energy sub metering", xlab= "")
par(new=T)
plot(DT$datetime,DT$Sub_metering_2,type="l",col= "red",axes = FALSE, xlab = "", ylab = "",ylim=range(c(DT$Sub_metering_1,DT$Sub_metering_2)))
par(new=T)
plot(DT$datetime,DT$Sub_metering_3,type="l",col="blue", xlab = "", ylab = "",axes = FALSE,ylim=range(c(DT$Sub_metering_1,DT$Sub_metering_2,DT$Sub_metering_3 )))
legend("topright",col = c("black","blue", "red"), legend = c("sub_metering_1", "sub_metering_2", "sub_metering_3"), lty= c(1,1,1))
par(new=F)
dev.off()